const express=require('express');
const path=require('path');
const cookieParser=require('cookie-parser');
const app=express();
const indexRouter=require('./routes/indexRouter');
const bannerRouter=require('./routes/bannerRouter');
app.use(express.static(path.resolve(__dirname,'./public')));
app.use(cookieParser());
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.set('views',path.resolve(__dirname,'./views'));
app.set('view engine','ejs');
app.use('/',indexRouter);
app.use('/banner',bannerRouter);
app.listen(3000);